name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test: ${{ matrix.test.name }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        test:
        - { name: "team-a"  }
        - { name: "team-b"  }
        - { name: "team-c"  }

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Tests
        run: pnpm --filter ${{ matrix.test.name }} test
